name: 🚀 Publish to NPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "package@updater.com"
      - run: git config --global user.name "Package Updater"
      - run: npm install
      - name: Commit code after npm install
        uses: stefanzweifel/git-auto-commit-action@v3
        with:
          commit_message: "Autocommit version patch"
      - name: 🚀 Publish to NPM
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - uses: stefanzweifel/git-auto-commit-action@v3
        with:
          commit_message: "New version upgrade"
          push: true
