name: npm publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: git commit -am "Before version patch"
      - run: npm version patch
      - run: npm run build
      - run: git commit -am "Bump version"
      - run: git push
      - run: cd dist
      - run: npm publish
